import type {
  ComponentSkuDefinition,
  Cost,
  MachineComponentSelection,
  MachineTemplateDefinition,
  ResearchId,
  TaskId,
} from "../types";

type ComponentSkuTier = "starter" | "compile" | "render" | "workstation" | "server";
type CatalogResearchId = Extract<
  ResearchId,
  "systemCatalog" | "customMachineAssembly"
>;

type CatalogComponentSkuDefinition = ComponentSkuDefinition & {
  tier: ComponentSkuTier;
  offTheShelf: true;
  unlockResearchId: CatalogResearchId;
};

type CatalogMachineTemplateDefinition = MachineTemplateDefinition & {
  tier: ComponentSkuTier;
  unlockResearchId: CatalogResearchId;
  intendedTasks: TaskId[];
};

const credits = (amount: number): Cost => ({
  resource: "credits",
  amount: Math.round(amount),
});

const data = (amount: number): Cost => ({
  resource: "data",
  amount: Math.round(amount),
});

export const componentSkus: CatalogComponentSkuDefinition[] = [
  {
    id: "cpu-barebones-1",
    name: "Barebones CPU",
    tier: "starter",
    type: "cpu",
    unlockResearchId: "systemCatalog",
    offTheShelf: true,
    description: "The single-core CPU package from the starting PC.",
    cost: [credits(6)],
    cpuPackageCount: 1,
    coreCount: 1,
    clockLevel: 1,
    cacheLevel: 1,
    cacheSpeedLevel: 1,
    schedulerSlots: 0,
  },
  {
    id: "cpu-sip-core",
    name: "SIP Core",
    tier: "starter",
    type: "cpu",
    unlockResearchId: "systemCatalog",
    offTheShelf: true,
    description: "Small off-the-shelf CPU package.",
    cost: [credits(1_250), data(18)],
    cpuPackageCount: 1,
    coreCount: 2,
    clockLevel: 6,
    cacheLevel: 8,
    cacheSpeedLevel: 6,
  },
  {
    id: "cpu-compile-die",
    name: "Compile Die",
    tier: "compile",
    type: "cpu",
    unlockResearchId: "systemCatalog",
    offTheShelf: true,
    description: "Balanced CPU package for chunked build work.",
    cost: [credits(4_800), data(36)],
    cpuPackageCount: 1,
    coreCount: 4,
    clockLevel: 10,
    cacheLevel: 10,
    cacheSpeedLevel: 10,
  },
  {
    id: "cpu-render-array",
    name: "Render Array",
    tier: "render",
    type: "cpu",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Dense CPU package tuned for frame work.",
    cost: [credits(18_000), data(72)],
    cpuPackageCount: 1,
    coreCount: 6,
    clockLevel: 14,
    cacheLevel: 12,
    cacheSpeedLevel: 14,
  },
  {
    id: "cpu-workstation-8",
    name: "Workstation Octa",
    tier: "workstation",
    type: "cpu",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Balanced workstation package for wider local work.",
    cost: [credits(58_000), data(130)],
    cpuPackageCount: 1,
    coreCount: 8,
    clockLevel: 17,
    cacheLevel: 14,
    cacheSpeedLevel: 17,
  },
  {
    id: "cpu-workstation-12",
    name: "Workstation Dodeca",
    tier: "workstation",
    type: "cpu",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "High-throughput workstation package for cache-heavy jobs.",
    cost: [credits(135_000), data(220)],
    cpuPackageCount: 1,
    coreCount: 12,
    clockLevel: 21,
    cacheLevel: 16,
    cacheSpeedLevel: 21,
  },
  {
    id: "cpu-ghz-16",
    name: "Workstation 16 Core Die",
    tier: "workstation",
    type: "cpu",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Wide workstation CPU at the local-die ceiling.",
    cost: [credits(420_000), data(360)],
    cpuPackageCount: 1,
    coreCount: 16,
    clockLevel: 24,
    cacheLevel: 18,
    cacheSpeedLevel: 24,
  },
  {
    id: "cpu-server-24",
    name: "Server 24 Core Die",
    tier: "server",
    type: "cpu",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Server-preview CPU for dense rack-node builds.",
    cost: [credits(760_000), data(620)],
    cpuPackageCount: 1,
    coreCount: 24,
    clockLevel: 28,
    cacheLevel: 20,
    cacheSpeedLevel: 28,
  },
  {
    id: "cpu-server-32",
    name: "Server 32 Core Die",
    tier: "server",
    type: "cpu",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Server-preview CPU for cache-rich batch work.",
    cost: [credits(1_400_000), data(900)],
    cpuPackageCount: 1,
    coreCount: 32,
    clockLevel: 31,
    cacheLevel: 22,
    cacheSpeedLevel: 31,
  },
  {
    id: "cpu-server-48",
    name: "Server 48 Core Die",
    tier: "server",
    type: "cpu",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Server-preview CPU for pre-cluster throughput.",
    cost: [credits(2_400_000), data(1_350)],
    cpuPackageCount: 1,
    coreCount: 48,
    clockLevel: 34,
    cacheLevel: 25,
    cacheSpeedLevel: 34,
  },
  {
    id: "cpu-server-64",
    name: "Server 64 Core Die",
    tier: "server",
    type: "cpu",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Highest current server-preview module.",
    cost: [credits(4_800_000), data(2_000)],
    cpuPackageCount: 1,
    coreCount: 64,
    clockLevel: 36,
    cacheLevel: 28,
    cacheSpeedLevel: 36,
  },
  {
    id: "ram-none",
    name: "No RAM",
    tier: "starter",
    type: "ram",
    unlockResearchId: "systemCatalog",
    offTheShelf: true,
    description: "The empty RAM bay from the starting PC.",
    cost: [],
    ramStickCount: 0,
    ramLevel: 0,
    ramSpeedLevel: 1,
  },
  {
    id: "ram-1kb-basic",
    name: "1 Kb RAM Kit",
    tier: "starter",
    type: "ram",
    unlockResearchId: "systemCatalog",
    offTheShelf: true,
    description: "Four 1 Kb sticks for first system tasks.",
    cost: [credits(1_100), data(30)],
    ramStickCount: 4,
    ramLevel: 3,
    ramSpeedLevel: 3,
  },
  {
    id: "ram-2kb-fast",
    name: "2 Kb RAM Kit",
    tier: "compile",
    type: "ram",
    unlockResearchId: "systemCatalog",
    offTheShelf: true,
    description: "Four 2 Kb sticks for chunked compile work.",
    cost: [credits(3_600), data(58)],
    ramStickCount: 4,
    ramLevel: 4,
    ramSpeedLevel: 5,
  },
  {
    id: "ram-4kb-work",
    name: "4 Kb RAM Kit",
    tier: "render",
    type: "ram",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Four 4 Kb sticks for render and regression work.",
    cost: [credits(12_000), data(96)],
    ramStickCount: 4,
    ramLevel: 5,
    ramSpeedLevel: 7,
  },
  {
    id: "ram-16kb-workstation",
    name: "16 Kb RAM Kit",
    tier: "workstation",
    type: "ram",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Four 16 Kb sticks for workstation staging.",
    cost: [credits(42_000), data(170)],
    ramStickCount: 4,
    ramLevel: 7,
    ramSpeedLevel: 9,
  },
  {
    id: "ram-64kb-workstation",
    name: "64 Kb RAM Kit",
    tier: "workstation",
    type: "ram",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Four 64 Kb sticks for broad local workloads.",
    cost: [credits(115_000), data(280)],
    ramStickCount: 4,
    ramLevel: 9,
    ramSpeedLevel: 11,
  },
  {
    id: "ram-256kb-workstation",
    name: "256 Kb RAM Kit",
    tier: "workstation",
    type: "ram",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Eight 256 Kb sticks for dense workstation builds.",
    cost: [credits(320_000), data(440)],
    ramStickCount: 8,
    ramLevel: 11,
    ramSpeedLevel: 13,
  },
  {
    id: "ram-512kb-server",
    name: "512 Kb RAM Kit",
    tier: "server",
    type: "ram",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Eight 512 Kb sticks for server-preview nodes.",
    cost: [credits(680_000), data(720)],
    ramStickCount: 8,
    ramLevel: 12,
    ramSpeedLevel: 15,
  },
  {
    id: "ram-2mb-server",
    name: "2 Mb RAM Kit",
    tier: "server",
    type: "ram",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Eight 2 Mb sticks for high-density batch systems.",
    cost: [credits(1_600_000), data(1_050)],
    ramStickCount: 8,
    ramLevel: 14,
    ramSpeedLevel: 17,
  },
  {
    id: "ram-8mb-server",
    name: "8 Mb RAM Kit",
    tier: "server",
    type: "ram",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Eight 8 Mb sticks for the current server-preview ceiling.",
    cost: [credits(3_400_000), data(1_600)],
    ramStickCount: 8,
    ramLevel: 16,
    ramSpeedLevel: 19,
  },
  {
    id: "scheduler-none",
    name: "No System Scheduler",
    tier: "starter",
    type: "scheduler",
    unlockResearchId: "systemCatalog",
    offTheShelf: true,
    description: "The empty scheduler bay from the starting PC.",
    cost: [],
    schedulerSlots: 0,
  },
  {
    id: "scheduler-2-slot",
    name: "2 Slot System Scheduler",
    tier: "starter",
    type: "scheduler",
    unlockResearchId: "systemCatalog",
    offTheShelf: true,
    description: "Basic system-level queue intake.",
    cost: [credits(800), data(18)],
    schedulerSlots: 2,
  },
  {
    id: "scheduler-4-slot",
    name: "4 Slot System Scheduler",
    tier: "compile",
    type: "scheduler",
    unlockResearchId: "systemCatalog",
    offTheShelf: true,
    description: "Enough system queue width for chunked local work.",
    cost: [credits(2_400), data(36)],
    schedulerSlots: 4,
  },
  {
    id: "scheduler-6-slot",
    name: "6 Slot System Scheduler",
    tier: "render",
    type: "scheduler",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Wide system queueing for dense machines.",
    cost: [credits(8_000), data(68)],
    schedulerSlots: 6,
  },
  {
    id: "scheduler-12-slot",
    name: "12 Slot System Scheduler",
    tier: "workstation",
    type: "scheduler",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Workstation backplane for heavy local queues.",
    cost: [credits(38_000), data(140)],
    schedulerSlots: 12,
  },
  {
    id: "scheduler-24-slot",
    name: "24 Slot System Scheduler",
    tier: "server",
    type: "scheduler",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Server-preview backplane for rack-node queues.",
    cost: [credits(420_000), data(520)],
    schedulerSlots: 24,
  },
  {
    id: "psu-barebones",
    name: "Barebones PSU",
    tier: "starter",
    type: "psu",
    unlockResearchId: "systemCatalog",
    offTheShelf: true,
    description: "The baseline power supply from the starting PC.",
    cost: [credits(2)],
    psuLevel: 1,
  },
  {
    id: "psu-compact",
    name: "Compact PSU",
    tier: "starter",
    type: "psu",
    unlockResearchId: "systemCatalog",
    offTheShelf: true,
    description: "Cheap power with little headroom.",
    cost: [credits(900)],
    psuLevel: 14,
  },
  {
    id: "psu-balanced",
    name: "Balanced PSU",
    tier: "compile",
    type: "psu",
    unlockResearchId: "systemCatalog",
    offTheShelf: true,
    description: "Safer rack-node power supply.",
    cost: [credits(2_800)],
    psuLevel: 18,
  },
  {
    id: "psu-headroom",
    name: "Headroom PSU",
    tier: "render",
    type: "psu",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "More capacity for dense chunked work.",
    cost: [credits(9_500)],
    psuLevel: 22,
  },
  {
    id: "psu-workstation",
    name: "Workstation PSU",
    tier: "workstation",
    type: "psu",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Power supply for dense workstation modules.",
    cost: [credits(46_000)],
    psuLevel: 27,
  },
  {
    id: "psu-server",
    name: "Server PSU",
    tier: "server",
    type: "psu",
    unlockResearchId: "customMachineAssembly",
    offTheShelf: true,
    description: "Power supply for the current server-preview ceiling.",
    cost: [credits(540_000)],
    psuLevel: 32,
  },
];

export const machineTemplates: CatalogMachineTemplateDefinition[] = [
  {
    id: "barebonesPc",
    name: "Barebones PC",
    tier: "starter",
    unlockResearchId: "systemCatalog",
    description: "The same minimal machine the game starts with.",
    intendedTasks: ["fetchBit", "decodeBit"],
    components: {
      cpu: "cpu-barebones-1",
      ram: "ram-none",
      scheduler: "scheduler-none",
      psu: "psu-barebones",
    },
  },
  {
    id: "starterNode",
    name: "Starter Node",
    tier: "starter",
    unlockResearchId: "systemCatalog",
    description: "A compact rack node for familiar system work.",
    intendedTasks: ["compileCode"],
    components: {
      cpu: "cpu-sip-core",
      ram: "ram-1kb-basic",
      scheduler: "scheduler-2-slot",
      psu: "psu-compact",
    },
  },
  {
    id: "compileBox",
    name: "Compile Box",
    tier: "compile",
    unlockResearchId: "systemCatalog",
    description: "A balanced box for Compile Code and Regression Test.",
    intendedTasks: ["compileCode", "regressionTest"],
    components: {
      cpu: "cpu-compile-die",
      ram: "ram-2kb-fast",
      scheduler: "scheduler-4-slot",
      psu: "psu-balanced",
    },
  },
  {
    id: "renderBrick",
    name: "Render Brick",
    tier: "render",
    unlockResearchId: "customMachineAssembly",
    description: "A dense node for Render Frame work.",
    intendedTasks: ["renderFrame", "regressionTest"],
    components: {
      cpu: "cpu-render-array",
      ram: "ram-4kb-work",
      scheduler: "scheduler-6-slot",
      psu: "psu-headroom",
    },
  },
  {
    id: "workstationTower",
    name: "Workstation Tower",
    tier: "workstation",
    unlockResearchId: "customMachineAssembly",
    description: "A high-throughput local workstation for dense batch work.",
    intendedTasks: ["compileCode", "renderFrame", "regressionTest"],
    components: {
      cpu: "cpu-ghz-16",
      ram: "ram-256kb-workstation",
      scheduler: "scheduler-12-slot",
      psu: "psu-workstation",
    },
  },
];

export const getComponentSku = (id: string) => {
  const sku = componentSkus.find((component) => component.id === id);
  if (!sku) throw new Error(`Unknown component SKU: ${id}`);
  return sku;
};

export const getMachineTemplate = (id: string) => {
  const template = machineTemplates.find((machine) => machine.id === id);
  if (!template) throw new Error(`Unknown machine template: ${id}`);
  return template;
};

export const getMachineComponentSkus = (selection: MachineComponentSelection) => [
  getComponentSku(selection.cpu),
  getComponentSku(selection.ram),
  getComponentSku(selection.scheduler),
  getComponentSku(selection.psu),
];
